version: "3.8"
services:
  mysqldb:
    image: mysql:8.2.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=coursenexus
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7.2
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/coursenexus
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379

volumes:
  mysql_data:
  redis_data:
